### ISSUE TITLE
[Bug]: Not Able To Change Anything On Local

### ISSUE THREAD

**Issue by Piyush-Use-Personal** [OpenSignLabs/OpenSign#1571]
### Issue Description

FYI: I don’t think this is a bug, but rather a configuration mistake on my end.

I’ve been trying to run OpenSign locally, and it seems to be working just fine. However, I wanted to add a small feature, a notification banner, at the top before self-hosting it. After modifying the docker-compose.yml to adjust the local setup, I am now unable to run it.

Changed file
```
version: '3.7'

services:
  server:
    build:
      context: ./apps/OpenSignServer
      dockerfile: Dockerfile
    container_name: OpenSignServer-container
    command: /usr/src/app/node_modules/.bin/nodemon server.js
    volumes:
      - ./apps/OpenSignServer/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    env_file: .env
    environment:
      - NODE_ENV=development
    networks:
      - app-network
  mongo:
    build:
      context: ./apps/mongo
      dockerfile: Dockerfile
    container_name: mongo-container
    volumes:
      - data-volume:/data/db
      - ./apps/mongo/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    ports:
      - "27017:27017"
    networks:
      - app-network
  client:
    build:
      context: ./apps/OpenSign
      dockerfile: Dockerfile
    container_name: OpenSign-container
    command: npm start
    env_file: .env
    volumes:
      - ./apps/OpenSign/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local
```
I also tried a few different versions, but none of them seem to be running the server.

The main error I encountered was: "The request path could not be found" on the frontend. However, the backend responds with: "opensign-server is running !!!"

Any help would be greatly appreciated.

![Image](https://github.com/user-attachments/assets/1265583b-d1ec-4cff-9536-e52913b7d916)

### Expected Behavior

I should be able to make changes locally before deploying on my infra

### Current Behavior

Page is not opening and saying 404

### Steps to reproduce

Use Docker-compose file attached

### Screenshots of the issue(optional)

![Image](https://github.com/user-attachments/assets/68e4cdf7-869a-42ad-bdf4-9c6510680b8a)

### Operating System [e.g. MacOS Sonoma 14.1, Windows 11]

windows 11

### What version of OpenSign™ are you seeing this issue on? [e.g. 1.0.6]

latest 

### What environment are you seeing the problem on?

Dev (localhost or vercel)

### Please check the boxes that apply to this issue report.

- [x] I have searched the existing issues & discussions to make sure that this is not a duplicate.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
- [x] I have searched the existing issues & discussions to make sure that this is not a duplicate.
