### ISSUE TITLE
Connectivity Issue with API Endpoint in Dockerized Environment

### ISSUE THREAD

**Issue by bandundu** [OpenSignLabs/OpenSign#231]
### Description
I am encountering a connectivity issue in my Dockerized application environment. The `OpenSignServer-container` is unable to connect to the open-sign-server API endpoint.

### Environment
- Docker version: 24.0.7, build afdd53b
- Host OS: Ubuntu 22.04.3 LTS x86_64
- Kernel: 5.15.0-88-generic
- Network Configuration: Docker bridge network

### Configuration Files
**docker-compose.yml**:
```yaml
version: '3.7'

services:
  server:
    build:
      context: ./apps/OpenSignServer
      dockerfile: Dockerfile
    image: opensignserver-image
    container_name: OpenSignServer-container
    command: /usr/src/app/node_modules/.bin/nodemon server.js
    volumes:
      - ./apps/OpenSignServer/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    env_file: .env
    environment:
      - NODE_ENV=development
    networks:
      - app-network
  mongo:
    build:
      context: ./apps/mongo
      dockerfile: Dockerfile
    container_name: mongo-container
    image: opensign-mongo
    volumes:
      - data-volume:/data/db
      - ./apps/mongo/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    ports:
      - "27017:27017"
    networks:
      - app-network
  client:
    build:
      context: ./apps/OpenSign
      dockerfile: Dockerfile
    image: opensign-image
    container_name: OpenSign-container
    command: npm start
    env_file: .env
    volumes:
      - ./apps/OpenSign/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local
```

**.env**:
```plaintext
# Frontend config
CI=false
PUBLIC_URL=http://[redacted-domain]/
GENERATE_SOURCEMAP=false
REACT_APP_SERVERURL=http://[redacted-api-domain]/api/app
REACT_APP_APPID=[redacted]
REACT_APP_GTM=[redacted]

# Backend ExpressJS config
APP_ID=[redacted]
appName=[redacted-app-name]
MASTER_KEY=[redacted-master-key]
MONGODB_URI=mongodb://[redacted-local-ip]:27017/OpenSignDB
PARSE_MOUNT=/app
SERVER_URL=http://[redacted-api-domain]/api/app

# Storage config
DO_SPACE=[redacted-storage-name]
DO_ENDPOINT=[redacted-do-endpoint]
DO_BASEURL=https://[redacted-storage-domain]
DO_ACCESS_KEY_ID=[redacted-access-key]
DO_SECRET_ACCESS_KEY=[redacted-secret-key]
DO_REGION=[redacted]

# Email mailgun config
MAILGUN_API_KEY=[redacted-api-key]
MAILGUN_DOMAIN=[redacted-domain]
MAILGUN_SENDER=[redacted-sender-email]

# Document signing certificate file
PFX_BASE64=/home/[redacted]/OpenSign/opensign.pfx

# Pass phrase for document
PASS_PHRASE=[redacted-pass-phrase]
```

### Symptoms
- `OpenSignServer-container` logs show a warning about inability to connect to '[redacted-api-url]'.
- This issue affects cloud code and push notifications. I can not register accoutns

### Steps to Reproduce
1. Start the Docker containers using `docker-compose up`.
2. Observe the logs of `OpenSignServer-container`.

### Attempted Solutions
- Verified API endpoint availability, inside and outside of container with curl. "open-sign-server is running !!!" is returned on a get to the [redacted-api-url] inside and outside of container, however [redacted-api-url]/api/app results in error not found or with webroser when i try to register i get: 

```html
Received an error with invalid JSON from Parse: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /api/app/users</pre>
</body>
</html>
```

- Tested network connectivity and DNS resolution within the container.
- Checked firewall and network policy restrictions.
- Ensured SSL/TLS certificates are correctly installed.
- Tried with http and https for API endpoint
- Tried with CI=false and CI=true in .env
- Tried both on local network and behind nginx reverse proxy
- Delete volumes and start from Scratch

### docker-compose up log on fresh install
my OpenSignServer-container log:
```bash
OpenSignServer-container  | Error: npm WARN logfile Error: EACCES: permission denied, scandir '/root/.npm/_logs'
OpenSignServer-container  | npm WARN logfile  error cleaning log files [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
OpenSignServer-container  | npm WARN logfile   errno: -13,
OpenSignServer-container  | npm WARN logfile   code: 'EACCES',
OpenSignServer-container  | npm WARN logfile   syscall: 'scandir',
OpenSignServer-container  | npm WARN logfile   path: '/root/.npm/_logs'
OpenSignServer-container  | npm WARN logfile }
OpenSignServer-container  |
OpenSignServer-container  |
OpenSignServer-container  | WARNING, Unable to connect to 'http://[redacted]:8080/api/app'. Cloud code and push notifications may be unavailable!
OpenSignServer-container  |
```

### Testing inside container

```bash
[redacted]@server:~/OpenSign$ docker exec -it OpenSignServer-container /bin/bash
root@38b3a29923de:/usr/src/app# curl http://[redacted]:8080/api/app
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /api/app</pre>
</body>
</html>
root@38b3a29923de:/usr/src/app# curl http://[redacted]:8080/api/
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /api/</pre>
</body>
</html>
root@38b3a29923de:/usr/src/app# curl http://[redacted]:8080
open-sign-server is running !!!root@38b3a29923de:/usr/src/app#
```

### Requested Assistance
Seeking guidance on resolving the connectivity issue to the API endpoint. Suggestions or troubleshooting steps from the community would be greatly appreciated.
