### ISSUE TITLE
[Bug]: issue on installing docker linux

### ISSUE THREAD

**Issue by killmasta93** [OpenSignLabs/OpenSign#663]
### Issue Description

getting issue on building the container 
```
 => ERROR [opensign-image 4/6] RUN npm install                                                                                                                                                                                              282.6s
 => [opensignserver-image 4/5] RUN npm install                                                                                                                                                                                              284.1s
 => => # npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.              
 => => # npm WARN deprecated request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142                                                                                                                      
 => => # npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.              
 => => # npm WARN deprecated subscriptions-transport-ws@0.11.0: The `subscriptions-transport-ws` package is no longer maintained. We recommend you use `graphql-ws` instead. For help migrating Apollo software to `graphql-ws`, see https://www.a
 => => # pollographql.com/docs/apollo-server/data/subscriptions/#switching-from-subscriptions-transport-ws    For general help using `graphql-ws`, see https://github.com/enisdenjo/graphql-ws/blob/master/README.md                              
 => => # npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.                                                                                                    
------
 > [opensign-image 4/6] RUN npm install:
#0 5.918 npm WARN ERESOLVE overriding peer dependency
#0 5.918 npm WARN While resolving: react-focus-lock@2.5.2
#0 5.919 npm WARN Found: react@18.2.0
#0 5.919 npm WARN node_modules/react
#0 5.920 npm WARN   react@"^18.2.0" from the root project
#0 5.920 npm WARN   107 more (@emotion/react, ...)
#0 5.920 npm WARN 
#0 5.920 npm WARN Could not resolve dependency:
#0 5.920 npm WARN peer react@"^16.8.0 || ^17.0.0" from react-focus-lock@2.5.2
#0 5.920 npm WARN node_modules/reactour/node_modules/react-focus-lock
#0 5.923 npm WARN   react-focus-lock@"2.5.2" from reactour@1.19.2
#0 5.923 npm WARN   node_modules/reactour
#0 5.923 npm WARN 
#0 5.923 npm WARN Conflicting peer dependency: react@17.0.2
#0 5.923 npm WARN node_modules/react
#0 5.923 npm WARN   peer react@"^16.8.0 || ^17.0.0" from react-focus-lock@2.5.2
#0 5.923 npm WARN   node_modules/reactour/node_modules/react-focus-lock
#0 5.923 npm WARN     react-focus-lock@"2.5.2" from reactour@1.19.2
#0 5.923 npm WARN     node_modules/reactour
#0 35.35 npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
#0 35.40 npm WARN deprecated rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser
#0 35.73 npm WARN deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
#0 36.46 npm WARN deprecated @babel/plugin-proposal-numeric-separator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-numeric-separator instead.
#0 36.75 npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
#0 36.82 npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
#0 38.54 npm WARN deprecated @babel/plugin-proposal-optional-chaining@7.21.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.
#0 44.09 npm WARN deprecated workbox-cacheable-response@6.6.0: workbox-background-sync@6.6.0
#0 44.49 npm WARN deprecated @babel/plugin-proposal-nullish-coalescing-operator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.
#0 44.95 npm WARN deprecated @babel/plugin-proposal-private-methods@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-private-methods instead.
#0 50.81 npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
#0 62.82 npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
#0 235.5 npm notice 
#0 235.5 npm notice New minor version of npm available! 10.5.0 -> 10.7.0
#0 235.5 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.7.0>
#0 235.5 npm notice Run `npm install -g npm@10.7.0` to update!
#0 235.5 npm notice 
#0 235.6 npm ERR! code ECONNRESET
#0 235.6 npm ERR! network aborted
#0 235.6 npm ERR! network This is a problem related to network connectivity.
#0 235.6 npm ERR! network In most cases you are behind a proxy or have bad network settings.
#0 235.6 npm ERR! network 
#0 235.6 npm ERR! network If you are behind a proxy, please make sure that the
#0 235.6 npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
#0 235.6 
#0 235.6 npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-05-04T23_38_42_069Z-debug-0.log
------
failed to solve: process "/bin/sh -c npm install" did not complete successfully: exit code: 1

```

### Expected Behavior

Currently my docker compose 

```
version: '3.7'

services:
  server:
    build:
      context: ./apps/OpenSignServer
      dockerfile: Dockerfile
    image: opensignserver-image
    container_name: OpenSignServer-container
    command: /usr/src/app/node_modules/.bin/nodemon server.js
    volumes:
      - ./apps/OpenSignServer/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8323:8080"
    depends_on:
      - mongo
    env_file: .env
    environment:
      - NODE_ENV=development
    networks:
      - app-network
  mongo:
    build:
      context: ./apps/mongo
      dockerfile: Dockerfile
    container_name: mongo-container
    image: opensign-mongo
    volumes:
      - data-volume:/data/db
      - ./apps/mongo/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    ports:
      - "27017:27017"
    networks:
      - app-network
  client:
    build:
      context: ./apps/OpenSign
      dockerfile: Dockerfile
    image: opensign-image
    container_name: OpenSign-container
    command: npm start
    env_file: .env
    volumes:
      - ./apps/OpenSign/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - "3300:3000"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local

```

the env
```

# Frontend config ************************************************************************************************************************************************************************************************

# Set it to the URL form where the app home page will be accessed
PUBLIC_URL=https://firmas.domain.com/
# Set it to true if you want to generate the Sourcemap for debugging
GENERATE_SOURCEMAP=false
# Set it to the URL from where APIs will be accessible, for local development it should be localhost:3000/api/app (use your local port number instead)
REACT_APP_SERVERURL=https://firmas.domain.com/api/app
# A 12 character long random app identifier. The value of this should be same as APP_ID which is a variable used by backend API.
REACT_APP_APPID=opensign
# Google tag manager container id for configuring GTM on all pages of the app
REACT_APP_GTM=GTM-123N7LD

# Backend ExpressJS config ****************************************************************************************************************************************************************************************
# A 12 character long random app identifier. The value of this should be same as REACT_APP_APPID which is a variable used by Frontend React App.
APP_ID=opensign
# Name of the app. It will be visible in the verification emails sent out.
appName=open_sign_server
# A 12 character long random secret key that allows access to all the data. It is used in Parse dashboard config to view all the data in the database.
MASTER_KEY=XnAadwKxxByMr
# Mongodb URI to connect to
MONGODB_URI=mongodb://username:password@localhost:27017
# Path on which APIs should be mounted. Do not change this. This variable shall be removed & value hardcoded in the source code in coming versions.
PARSE_MOUNT=/app
# Set it to the URL from where APIs will be accessible to the NodeJS functions, for local development it should be localhost:3000/api/app (use your local port number instead)
SERVER_URL=https://firmas.domain.com/api/app

# Storage config ************************************************************************************************************************************************************************************************
# Digital ocean space name or AWS S3 bucket name for uploading documents
DO_SPACE=DOSPACENAME
# Digital ocean spaces endpoint or AWS S3 endpoint for uploading documents
DO_ENDPOINT=ams3.digitaloceanspaces.com
# Digital ocean baseurl or AWS S3 base URL
DO_BASEURL=https://DOSPACENAME.ams3.digitaloceanspaces.com
# Digital ocean spaces access key ID or AWS s3 Access key ID for uploading the docs
DO_ACCESS_KEY_ID=
# Digital ocean spaces secret access key or AWS s3 secret access key for uploading the docs
DO_SECRET_ACCESS_KEY=
# Digital ocean spaces region or AWS s3 region
DO_REGION=us-west
# Set this to true id you are using local storage instead of s3 compatible storage
USE_LOCAL=TRUE

# Email mailgun or set SMTP_ENABLE true to use SMTP config (The app will not initialize if any of these 3 variables are not set) *********************************************************************************************************************
MAILGUN_API_KEY=XXXXX
MAILGUN_DOMAIN=mail.yourdomain.com
MAILGUN_SENDER=postmaster@mail.yourdomain.com
SMTP_ENABLE=true
SMTP_HOST=mail.domain.com.co
SMTP_PORT=465
SMTP_USER_EMAIL=xxxxx@domain.com.co
SMTP_PASS=xxxxxxx

# Base64 encoded PFX or p12 document signing certificate file *********************************************************************************************************************
PFX_BASE64=

# Provide Pass pharse of above PFX or p12 document
PASS_PHRASE=opensign

```

### Operating System [e.g. MacOS Sonoma 14.1, Windows 11]

ubuntu 20 LTS

### What version of OpenSign™ are you seeing this issue on? [e.g. 1.0.6]

latest

### What environment are you seeing the problem on?

Hosted (app.yourdomain.com)

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.
